<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pAccountInformationLabel</name>
   <tag></tag>
   <elementGuidId>71fd8159-967a-4527-a1c4-9d2173bf3326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Account Information')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b3996641-4a40-441d-a3fd-557f625f6b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Account Information</value>
      <webElementGuid>6e47fb3a-e7f2-4536-964e-212a4662e30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;pageTabs&quot;]/div[@class=&quot;accountInformationTab&quot;]/p[1]</value>
      <webElementGuid>e3984db5-dda4-4bd1-a6bc-8389b04f954a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div/div/p</value>
      <webElementGuid>519b2e95-e9b3-40ae-95ec-f0fef426ac21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//p[(text() = 'Account Information')]</value>
      <webElementGuid>6d8145a9-4051-4712-811f-a0381e22c140</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
