<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pAddressInformationLabel</name>
   <tag></tag>
   <elementGuidId>28718cc2-e4da-4360-9d4b-360444d04764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.addressInformationTab > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'Address Information')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>e7550e28-9042-48bd-a92b-59ff6fd55a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Address Information</value>
      <webElementGuid>8d74903c-cdfb-4737-9ff4-1ab5da19d960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;pageTabs&quot;]/div[@class=&quot;addressInformationTab&quot;]/p[1]</value>
      <webElementGuid>c018a88d-69b1-485b-a3a8-2b33969eb60f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div/div[2]/p</value>
      <webElementGuid>0c8c1245-ee50-4bba-8bed-81b17657fc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::p[2]</value>
      <webElementGuid>69514acd-15fa-414a-a66f-0eefbfce9c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payments'])[1]/following::p[2]</value>
      <webElementGuid>4744dd5a-4250-476d-92a4-c1b674e28a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERSONAL INFORMATION'])[1]/preceding::p[1]</value>
      <webElementGuid>bdb5254c-7e34-4799-9a5f-876243c27dde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Address Information']/parent::*</value>
      <webElementGuid>89ffcc08-8ef0-4eb4-8040-bab9ff489415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>580c852a-a68b-4790-b529-8b55607cd104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Address Information' or . = 'Address Information')]</value>
      <webElementGuid>48590f32-c965-4ea0-ae23-e792a6e2f458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
