<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSave</name>
   <tag></tag>
   <elementGuidId>58724845-c6db-4be8-bad7-ea7400681e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class = 'og-button undefined false og-primary medium ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btnSave.button
div.boMainContent--wrapper div.boMainContent div.boMainContent__content div.boPages div.accountInformation:nth-child(3) div.accountInformation__content div.accountInformationSection div.accountInformationSection__content div.infoBlock-password div.infoBlock-password__content div.blockContent div.accountPasswordForm div.row div.formAction div.actions:nth-child(4) > button.og-button.undefined.false.og-primary.medium:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>722dbd47-83af-4c42-9612-125e8db8b1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>774ff401-3465-4176-bca7-6396a48d53d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-default button-secondary mt-5  btnSave button</value>
      <webElementGuid>a6981680-aa0b-49d5-ac02-c5544a630985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>83695cdb-2eaf-4e0f-a275-9ae074ce7dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;addressInformationSection&quot;]/div[@class=&quot;addressInformationSection__content&quot;]/div[@class=&quot;newAddressForm&quot;]/div[@class=&quot;newAddressForm__content&quot;]/div[@class=&quot;contentBlock&quot;]/form[@class=&quot;ant-form ant-form-horizontal&quot;]/div[@class=&quot;dualInput formAction&quot;]/button[@class=&quot;ant-btn ant-btn-default button-secondary mt-5  btnSave button&quot;]</value>
      <webElementGuid>c308b5de-a247-491e-9e53-b863716b6768</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>b35eb495-2d88-4462-9346-7cb3bad70ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div[2]/div/div/div/div[2]/form/div[7]/button</value>
      <webElementGuid>56124146-1754-4242-b41f-4606f3ce8437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belgrade'])[1]/following::button[1]</value>
      <webElementGuid>e23fe06d-3bf9-4392-a549-a400930794ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serbia'])[1]/following::button[1]</value>
      <webElementGuid>364cb82c-1b55-46dd-becf-6bd28eebcd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[1]</value>
      <webElementGuid>ebfe8e0a-2165-4ec1-9632-fb206a376f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>65e739a5-ff79-4c58-855e-4ac698cd06c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>54fe5cd8-fecd-4e7c-925f-3ad91480ddd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//button[@class = 'og-button undefined false og-primary medium ']</value>
      <webElementGuid>50b8674e-7d9d-4105-bef5-2b7c58f4438e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
