<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEnterOldPassword</name>
   <tag></tag>
   <elementGuidId>3ee373b5-ff7e-4305-ba02-64f54d385d40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter old password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85c9ce50-0def-47a0-a10a-1632b6ce225d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c8c76a2a-128d-4d39-9627-5d66dd7bb0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter old password</value>
      <webElementGuid>3568317b-f35e-4399-a3f0-ab2fe5393d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>adbe903a-d16c-4b5e-ba80-530aca3c17c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;accountInformationSection&quot;]/div[@class=&quot;accountInformationSection__content&quot;]/div[@class=&quot;infoBlock-password&quot;]/div[@class=&quot;infoBlock-password__content&quot;]/div[@class=&quot;blockContent&quot;]/div[@class=&quot;accountPasswordForm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;formAction&quot;]/div[@class=&quot;inputField&quot;]/div[@class=&quot;inputElement&quot;]/input[1]</value>
      <webElementGuid>ec80488d-57af-4c16-898f-d26d1b977670</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='S']</value>
      <webElementGuid>c63f91b0-9126-4e6e-ab2b-021bc7588488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>e70234e5-d936-4f39-bfff-869bf477c8e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e8f9d921-7ce0-49a6-8b68-824983f87760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter old password']</value>
      <webElementGuid>78cf7da2-017d-4cd0-931a-3a36ffe62691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
