<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputReEnterNewPassword</name>
   <tag></tag>
   <elementGuidId>f7759670-fd51-442b-aa69-02a5995d961a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Re-enter new password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5daf26e2-b5d4-462a-b015-d1c2c840ff51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>707635d5-014c-4fe4-978e-0d82db92a4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-enter new password</value>
      <webElementGuid>8f84872b-fbb1-4ca7-91a2-bd1677077ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>b16c1a5c-5c09-4754-b3c6-be44544cc8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;accountInformationSection&quot;]/div[@class=&quot;accountInformationSection__content&quot;]/div[@class=&quot;infoBlock-password&quot;]/div[@class=&quot;infoBlock-password__content&quot;]/div[@class=&quot;blockContent&quot;]/div[@class=&quot;accountPasswordForm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;formAction&quot;]/div[@class=&quot;inputField&quot;]/div[@class=&quot;inputElement&quot;]/input[1]</value>
      <webElementGuid>fa892b04-732e-4864-b871-ef0ee7225503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='T']</value>
      <webElementGuid>0d209703-6a23-4977-9007-5a07852e998f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[2]/div/div/div/div[3]/div/input</value>
      <webElementGuid>5f06c066-ddc5-41e2-9d4d-1d47fd51bf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>8c1b16ea-382c-4842-8740-d399610681f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Re-enter new password']</value>
      <webElementGuid>94f2e7a2-67ed-4379-97d7-5a2831a01780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
