<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEnterNewPassword</name>
   <tag></tag>
   <elementGuidId>6be13054-3955-4080-90ec-8dbb41f1fc27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder='Enter new password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65b696ef-b1ab-4707-b30d-e66ac07547cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b13c8fb6-2c7a-42f7-b9e8-161c6c01ed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter new password</value>
      <webElementGuid>4f2598c2-ae5a-4484-906f-fb01cfe1d45a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;accountInformation&quot;]/div[@class=&quot;accountInformation__content&quot;]/div[@class=&quot;accountInformationSection&quot;]/div[@class=&quot;accountInformationSection__content&quot;]/div[@class=&quot;infoBlock-password&quot;]/div[@class=&quot;infoBlock-password__content&quot;]/div[@class=&quot;blockContent&quot;]/div[@class=&quot;accountPasswordForm&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;formAction&quot;]/div[@class=&quot;inputField&quot;]/div[@class=&quot;inputElement&quot;]/input[1]</value>
      <webElementGuid>37162173-555e-481d-9736-f13a4cba854b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>7e1328e8-563a-49f7-80a3-33646844a861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>8825bca7-be01-4a46-86a6-fa4834884b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>94398152-d36e-41aa-b449-d0ed4b95dc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter new password']</value>
      <webElementGuid>c99c7113-c9f4-4b6c-a98e-3604b2a62faa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
