<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconShoppingBag</name>
   <tag></tag>
   <elementGuidId>b9fe1206-c67c-4fa9-aef1-2cd1bf20e4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href= '/shopping-bag']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.header-item.header-item--rounded.animated</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36cd498f-eb01-4cda-9a6e-9b130c74a284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shopping-bag</value>
      <webElementGuid>17c3df75-b6e9-42b6-a292-818bd4612e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-item header-item--rounded animated</value>
      <webElementGuid>d4b9b47c-a046-4f42-a80a-33f853da20c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>28f01fec-93f6-4bcb-b787-4fcfd6d72cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSticky&quot;)/div[@class=&quot;header-new-design__top ps-container&quot;]/div[@class=&quot;header-new-design__top__actions&quot;]/a[@class=&quot;header-item header-item--rounded animated&quot;]</value>
      <webElementGuid>12cf5115-1dcc-4556-a7b2-01dc875ab50d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='headerSticky']/div/div[3]/a[3]</value>
      <webElementGuid>a221899e-ccf2-4705-930a-15a216feb7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/following::a[3]</value>
      <webElementGuid>285d5c99-1ed9-4560-9e04-d52a3a0169e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping on Mark Severs store | mark@getthesystem.com'])[1]/preceding::a[1]</value>
      <webElementGuid>d90dba52-dc5b-4933-a510-201d5c13cd0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for?'])[1]/preceding::a[1]</value>
      <webElementGuid>1c2ab102-baa5-4d38-9c63-2f64b89b3caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/shopping-bag')])[2]</value>
      <webElementGuid>1d34d101-7ffa-4f93-9bfb-2543a0d29c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>6544c782-a029-4640-9995-af0cd7045766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shopping-bag' and (text() = '8' or . = '8')]</value>
      <webElementGuid>42e8c3ba-6f95-4119-ab9a-f3e71aa9389c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
