<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconGuestProfile</name>
   <tag></tag>
   <elementGuidId>02c162fa-e44a-4e02-8f07-f8caa4cc57c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'userIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.userIcon > a > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>56ed13f0-0e20-4a61-b85c-c58b0839da0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>433fed2d-c07b-4553-a730-063bdc572052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>c983ae4a-7613-4f35-81ca-6acbc339bda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 41 41</value>
      <webElementGuid>99f9aabd-3e00-45e5-9d35-096eac474ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>cc2a03fa-6761-4216-a0a4-4acef369d733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>6dd7c085-3924-46b0-af76-45c32f9db609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSticky&quot;)/div[@class=&quot;header-new-design__top ps-container&quot;]/div[@class=&quot;header-new-design__top__actions&quot;]/div[@class=&quot;userIcon&quot;]/a[1]/svg[1]</value>
      <webElementGuid>82e130a0-3fd4-47bc-9c38-bcd7af2b7b45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='vat'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>8bc424e6-d8d5-40bc-b518-efd8fdc95036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping on Mark Severs store | mark@getthesystem.com'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>9872d1e6-502c-46dc-aef2-e9b615ba9bc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
