<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iconUserProfile</name>
   <tag></tag>
   <elementGuidId>ff2f4539-86da-418e-bebe-ccd38e91ce24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'letterIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.letterIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a372334-d5b3-4876-9d16-48914682be18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>letterIcon</value>
      <webElementGuid>c0b87f86-0cbb-4ad1-99df-68d21c44514a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>08283d28-8e9e-4e50-ac03-a87dc2b66876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSticky&quot;)/div[@class=&quot;header-new-design__top ps-container&quot;]/div[@class=&quot;header-new-design__top__actions&quot;]/div[@class=&quot;avatarMenuItem&quot;]/div[@class=&quot;avatar&quot;]/div[@class=&quot;avatar__content&quot;]/div[@class=&quot;letterIcon&quot;]</value>
      <webElementGuid>0c182e68-d507-4833-9eb1-164bf2ab0020</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='headerSticky']/div/div[3]/div[2]/div/div/div</value>
      <webElementGuid>01660987-b4a5-4817-8824-c2f174026aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping on Mark Severs store | mark@getthesystem.com'])[1]/preceding::div[1]</value>
      <webElementGuid>3b11d369-d790-4ac5-88cc-2512f5a0c249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What are you looking for?'])[1]/preceding::div[2]</value>
      <webElementGuid>cafb1050-5d00-46ba-8ada-1604d4444de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='S']/parent::*</value>
      <webElementGuid>0207ebf9-8ec0-4ea2-b0c6-90cde0b934ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>392000ed-42a1-481c-8370-2a0a43f9fe9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'S' or . = 'S')]</value>
      <webElementGuid>e49bf9ac-88da-475c-9dbf-3746e1b72449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@class = 'letterIcon']</value>
      <webElementGuid>1555fbff-c906-4db1-95c7-57bd4a28a913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
