<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgLogo</name>
   <tag></tag>
   <elementGuidId>b7de9858-8e9e-48a2-acf6-2278a344f3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='headerSticky']/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>44007ee0-96a8-43df-8122-7a6bc353d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://globalupload-test.s3.ca-central-1.amazonaws.com/images/organo_christmas_logo_20221209145542183.png</value>
      <webElementGuid>5b5209c4-87ee-4a95-aa29-3ced0c76fad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Logo</value>
      <webElementGuid>7838fca7-7925-4be1-86c0-461b7d247ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerSticky&quot;)/div[@class=&quot;header-new-design__top ps-container&quot;]/div[@class=&quot;header-new-design__top__logo&quot;]/a[1]/img[1]</value>
      <webElementGuid>b080a8c5-8a32-4a64-8e44-5034c9a73efe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='headerSticky']/div/div/a/img</value>
      <webElementGuid>4ad5a78a-b23c-4b18-95d4-c8fea25ccf02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Logo']</value>
      <webElementGuid>a15bd1c0-2dd7-441c-82d5-1de2afdd00b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e117064e-470b-4790-a6ca-1835299a1d47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://globalupload-test.s3.ca-central-1.amazonaws.com/images/organo_christmas_logo_20221209145542183.png' and @alt = 'Logo']</value>
      <webElementGuid>0c34d75a-93b3-4026-862d-88eb9a45d6f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
