<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svgShowPasswordLogin</name>
   <tag></tag>
   <elementGuidId>67129bd1-3e7a-4c81-8e7c-2a3c5e065fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//i[@class=&quot;pi pi-eye&quot;])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ant-input-suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb1cca5f-a0a9-4432-baf4-239a34124328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-suffix</value>
      <webElementGuid>1494d675-394d-4bd8-b0c5-7a839a898378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_password&quot;)/span[@class=&quot;ant-input-affix-wrapper ant-input-password undefined pass-input ant-input-affix-wrapper-status-success&quot;]/span[@class=&quot;ant-input-suffix&quot;]</value>
      <webElementGuid>361080fc-3a0c-4976-ba43-365387f2f04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='user_password']/span/span</value>
      <webElementGuid>34aa5399-4dea-4430-a672-f9e101f615e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::span[2]</value>
      <webElementGuid>9d3f5e0f-6eca-4691-bac9-b243a3526e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>9c5b1905-21e3-4240-850f-600b26d19fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register a new account?'])[1]/preceding::span[2]</value>
      <webElementGuid>a921911d-d976-40d1-bd66-78ad0f0afec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscribe'])[1]/preceding::span[2]</value>
      <webElementGuid>1245475e-908e-4454-8457-9c775764705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>5e163698-8cf5-46e3-8df6-f8dbc058b775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
