<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ahrefFirstInvoiceBO</name>
   <tag></tag>
   <elementGuidId>75a46468-331f-4e82-ac4f-b6cbc29f00b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class= 'row-invoice'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row-invoice > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0ad94b6d-5583-414a-a3ac-b606fac5bc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://globalupload-test.s3.ca-central-1.amazonaws.com/documents/inv_21159376_20230206143744193.pdf</value>
      <webElementGuid>70dd293f-5fd2-4087-9ed6-e7d63a3e5669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>blank</value>
      <webElementGuid>ba32fedf-444a-4934-8aed-e463fb6b666d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>download</name>
      <type>Main</type>
      <value>invoice</value>
      <webElementGuid>b65e8fbd-a85b-4d15-97c6-b8866b2229cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>21159376</value>
      <webElementGuid>7fbc9efd-fa38-44d0-b071-da98dc74364c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;viewOrdersPage&quot;]/div[@class=&quot;viewOrdersPage__content&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion__content&quot;]/div[@class=&quot;accordion__body&quot;]/div[@class=&quot;table&quot;]/div[@class=&quot;tableMainViewOrders&quot;]/div[@class=&quot;tableMainViewOrders__content&quot;]/div[@class=&quot;tableContent&quot;]/div[@class=&quot;tableRow&quot;]/div[@class=&quot;tableRow__content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;invoiceData-wrapper&quot;]/div[@class=&quot;tableData&quot;]/div[@class=&quot;tableData__content&quot;]/div[@class=&quot;row-invoice&quot;]/a[1]</value>
      <webElementGuid>99db1e25-c8f8-4654-a505-6f08fb747d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div/div[3]/div/div/div/div[4]/div/div/div/a</value>
      <webElementGuid>926fa91b-ca80-46a2-b996-2810b8ab4b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'21159376')]</value>
      <webElementGuid>578bab7a-e408-4fe8-aeaa-6098d8e635c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data'])[1]/following::a[1]</value>
      <webElementGuid>1dab2f5e-08f3-4370-9940-61c4639ebefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order History'])[1]/following::a[1]</value>
      <webElementGuid>7b069749-01d7-4e58-acfb-b82f64363123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR 225.00'])[1]/preceding::a[1]</value>
      <webElementGuid>1a40417b-60c9-4a3d-b661-5d634b58309f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paid'])[1]/preceding::a[1]</value>
      <webElementGuid>1d29a889-74ac-4199-9e94-b79f9d6a035d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='21159376']/parent::*</value>
      <webElementGuid>2850468f-d32f-47cf-90ca-eb8e75a27bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://globalupload-test.s3.ca-central-1.amazonaws.com/documents/inv_21159376_20230206143744193.pdf')]</value>
      <webElementGuid>dc998e42-05ac-4982-84fa-2a89bc439f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/a</value>
      <webElementGuid>6d38cf68-b01d-45fc-85b8-69017c619791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://globalupload-test.s3.ca-central-1.amazonaws.com/documents/inv_21159376_20230206143744193.pdf' and (text() = '21159376' or . = '21159376')]</value>
      <webElementGuid>c6c302a5-8faa-4507-9ea3-3ebcd6a43532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//div[@class= 'row-invoice'])[1]</value>
      <webElementGuid>fb314bc3-30b6-4c6d-9e15-d3e7a9fa332c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
