<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg1ViewDetailOrder</name>
   <tag></tag>
   <elementGuidId>74e1101c-7f5e-433e-a6ef-d3ab6572e838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div[@class= 'openDetailView'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.openDetailView > svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>dd25764f-66ad-4ab6-9ebf-a90603bedee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>844baa60-9cbe-4ae7-8680-1f51d6bebf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b47eff0a-6eee-4f26-b864-b4e85b3f6aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>eye-invisible</value>
      <webElementGuid>19848dcf-8a9a-4215-976e-a2cc14e1f507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>fcb7fe61-033a-4d4b-8edb-aad386b9a5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>af06bbbb-df45-4b2d-89e2-194545e82ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>df50cc65-d493-4d79-9ff9-8f04f2936abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8561673-9c62-428e-abae-13022a748080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;viewOrdersPage&quot;]/div[@class=&quot;viewOrdersPage__content&quot;]/div[@class=&quot;accordion&quot;]/div[@class=&quot;accordion__content&quot;]/div[@class=&quot;accordion__body&quot;]/div[@class=&quot;table&quot;]/div[@class=&quot;tableMainViewOrders&quot;]/div[@class=&quot;tableMainViewOrders__content&quot;]/div[@class=&quot;tableContent&quot;]/div[@class=&quot;tableRow&quot;]/div[@class=&quot;tableRow__content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row-actions-wrapper&quot;]/div[@class=&quot;tableData&quot;]/div[@class=&quot;tableData__content&quot;]/div[@class=&quot;row-actions&quot;]/div[@class=&quot;openDetailView&quot;]/svg[1]</value>
      <webElementGuid>80f2ea13-78c1-48b1-a131-e08a057b40ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>58a4ab77-a154-46ca-a619-e8646729ed00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//div[@class= 'openDetailView'])[1]</value>
      <webElementGuid>7eff9849-9fd0-4b0f-a4f2-166575c06635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
