<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divFirstSelectPaymentMethod</name>
   <tag></tag>
   <elementGuidId>cf6b7d30-642b-44c5-a94e-4341c4b4b71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type = 'radio'])[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.p-radiobutton-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7f62aec5-c4dd-4fb9-9118-6bbc78b0f4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-radiobutton-icon</value>
      <webElementGuid>8f0752b3-2deb-434f-bc40-3ada7401bd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;boMainContent--wrapper&quot;]/div[@class=&quot;boMainContent&quot;]/div[@class=&quot;boMainContent__content&quot;]/div[@class=&quot;boPages&quot;]/div[@class=&quot;viewPayment&quot;]/div[@class=&quot;viewPayment__content&quot;]/div[@class=&quot;paper__body&quot;]/div[@class=&quot;paper__body__content&quot;]/div[@class=&quot;selectPaymentMethodView&quot;]/div[@class=&quot;selectPaymentMethodView__content&quot;]/div[@class=&quot;selectPaymentMethodView__content__body&quot;]/div[@class=&quot;selectPaymentMethodView__content__body__item&quot;]/span[@class=&quot;radio&quot;]/div[@class=&quot;p-radiobutton p-component p-radiobutton-checked&quot;]/div[@class=&quot;p-radiobutton-box p-highlight&quot;]/div[@class=&quot;p-radiobutton-icon&quot;]</value>
      <webElementGuid>94c874a6-56a3-4dde-85cc-0c14a46ecb4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div/span/div/div[2]/div</value>
      <webElementGuid>e0b24ee7-919e-4757-8a5c-92f0f7f7d91e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/div</value>
      <webElementGuid>4ea39e8e-f10d-484e-9cc6-0f020868760d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//span[@class = 'radio '])[1]</value>
      <webElementGuid>b566a078-f1f4-4b80-8d8d-979810c77966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//input[@type = 'radio'])[1]</value>
      <webElementGuid>f3ba108f-9597-44d1-9cc2-ae3a15805b59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
