<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCardNumber</name>
   <tag></tag>
   <elementGuidId>4be5606b-baff-41f4-a7dd-f47b7e19bb43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95698f16-abec-47bb-8c7d-6957aa404db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>53a60a4a-5a56-44ea-9fd1-022a88d1d7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87675ce3-75da-4349-adee-4fdee32b3baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>7f547cfc-9fd0-44cb-8c59-ef33c2e10c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputmask p-filled</value>
      <webElementGuid>a2650943-94cd-43ab-9b23-46439f09c773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number&quot;)</value>
      <webElementGuid>4aa66756-1b7f-4df2-82a9-0b86a7f7f151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number']</value>
      <webElementGuid>e33be072-1b51-41c7-8b61-c1c977135976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div/form/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>6b561a62-46dd-41e2-8daa-1c320f2d72f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>49b44e0d-2a61-4858-ad4a-d8a4e4c2de06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'card_number' and @type = 'text' and @name = 'card_number']</value>
      <webElementGuid>93d42865-33fd-44cf-98ef-f3eb2a8d7bc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
