<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCVV</name>
   <tag></tag>
   <elementGuidId>2e26b069-19a3-47b3-be20-99b355965435</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cvv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f20daa94-e018-4a08-9e4f-78b657a1535a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>cbd328f2-520c-4358-8e22-2a52800eaab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be87d8c2-f662-48d4-acc0-8d25d711bdcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvv</value>
      <webElementGuid>b3e468ac-da03-4415-b5d5-09300c1e0778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component p-inputmask p-filled</value>
      <webElementGuid>30ed1c54-75ae-46d4-ba2a-fef376071a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvv&quot;)</value>
      <webElementGuid>dfca759a-918c-4d1b-abae-9b80b4a6a700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvv']</value>
      <webElementGuid>8aed71cf-b8d7-45c1-b2b4-a73e45c0dbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div/form/div/div/div/div[3]/div[3]/span/input</value>
      <webElementGuid>4717fa79-f2ec-4b62-aab2-2fddfda43ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/input</value>
      <webElementGuid>9266794b-0305-4b74-af97-2c712e095557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cvv' and @type = 'text' and @name = 'cvv']</value>
      <webElementGuid>f0e6c16f-7a1e-408b-936f-f9345613f74a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
