<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCardHolder</name>
   <tag></tag>
   <elementGuidId>6ae18694-0c47-4dc5-8960-6dd75180c00a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cardholder_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cardholder_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cd96cd4d-0309-4fbd-b23a-074d6a29eae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cardholder_name</value>
      <webElementGuid>bc860f65-3c57-4f23-a50a-2fdd8b833374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cardholder_name</value>
      <webElementGuid>92990aa8-60de-40c6-9f55-3fea8b217756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-inputtext p-component</value>
      <webElementGuid>5ae0a991-97f8-4065-ae1a-2375a7996840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cardholder_name&quot;)</value>
      <webElementGuid>d8e0ff9a-b3e4-4977-894b-10adf659320e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cardholder_name']</value>
      <webElementGuid>87d6a6b4-85a5-430d-b6c6-db90cd45073a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/div[2]/div/div[2]/div/div/div/div/div/div/form/div/div/div/div/div/span/input</value>
      <webElementGuid>37dd0d4f-add8-47f3-a1e9-8d7c9120c00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>60581825-fc35-4d1b-ae74-50ff9e6b3500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cardholder_name' and @name = 'cardholder_name']</value>
      <webElementGuid>6d4ae45d-ace6-4b95-9a06-f3f7f4e7a9fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
