<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divCountryDropdown</name>
   <tag></tag>
   <elementGuidId>10899527-c92d-4478-8447-b9d26f3add8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='country']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='country']</value>
      <webElementGuid>9bbfc906-9408-48e5-ae4f-f20c6750726f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
