<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputStreetAddress</name>
   <tag></tag>
   <elementGuidId>ab21c953-0d33-4c2f-aae1-75428777248f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ant-input-status-success.rec.w-100.mr-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='street_address_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a4358d4-863a-4c21-8b07-8de41b5b3dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2cc0333-1c59-4979-9f24-8fcd96998763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Street address or P.O Box</value>
      <webElementGuid>98ba94c6-a8cd-407a-a810-44704d707629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success rec w-100  mr-0</value>
      <webElementGuid>3c843e44-f1bf-4d47-9350-7c61ac616ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>6465fc73-bf09-44ed-bc61-af7d85121b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;street_address_1&quot;)/input[@class=&quot;ant-input ant-input-status-success rec w-100  mr-0&quot;]</value>
      <webElementGuid>1cd83940-5c1d-4e21-b37f-5d6480c6493d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='t']</value>
      <webElementGuid>c6d46820-ab2b-40fe-a107-35658e0fca81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='street_address_1']/input</value>
      <webElementGuid>9e833572-f0b2-4f56-a339-47ea955780a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/fieldset/input</value>
      <webElementGuid>049da564-4724-46ad-9dac-5038299ee4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Street address or P.O Box']</value>
      <webElementGuid>41f032be-d5de-4e27-9e22-ac074d05e0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
