<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputZipOrPostalCode</name>
   <tag></tag>
   <elementGuidId>3755ab41-1318-4827-9aaa-61078b4c53be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postal_code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#postal_code > input.ant-input.ant-input-status-success.w-100.mr-0.rec</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5cc4ad3-68c4-4115-9725-d18f7425164a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85d4940c-7950-4d21-991e-2d125d2b1ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Zip or Postal Code</value>
      <webElementGuid>7860a4d5-4136-4cb9-9d96-0950f3c92e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success w-100  mr-0 rec</value>
      <webElementGuid>defe6077-ff39-4934-9964-e5891b9e0297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>62a18c67-1fee-4458-9f3a-5e528c1f0133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postal_code&quot;)/input[@class=&quot;ant-input ant-input-status-success w-100  mr-0 rec&quot;]</value>
      <webElementGuid>2564e859-af63-4d7a-9557-8e6b0dfe0291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='1'])[2]</value>
      <webElementGuid>26cc1dbe-8a86-40af-bd1c-293627990bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='postal_code']/input</value>
      <webElementGuid>69881d3a-e40b-4991-9310-6b86b09cb996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/fieldset/input</value>
      <webElementGuid>97156fbd-f0f2-4c81-b550-33c4669a3ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Zip or Postal Code']</value>
      <webElementGuid>21fcf253-3eb6-432c-9e2d-50613e2f213b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id='postal_code']</value>
      <webElementGuid>658dee86-2c2c-4205-921c-46ec1aafa2c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
