<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputShippingLastName</name>
   <tag></tag>
   <elementGuidId>c0bfe3ca-5e39-467b-97ed-4f30d0925935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneNumberLabel_last_name > input.ant-input.ant-input-status-success.rec.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a5c043c-e139-4082-bb9a-6bbadfcff550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5da626ff-6f5e-4ed5-9207-780f70ba16ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>598d15a5-7c5f-4b39-8bd9-3bb9ef34662d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success rec w-100</value>
      <webElementGuid>f5efdea4-2161-4c7b-b915-c3ff878d7dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>d45b87ae-0c0a-4403-8852-66301b2254cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumberLabel_last_name&quot;)/input[@class=&quot;ant-input ant-input-status-success rec w-100&quot;]</value>
      <webElementGuid>4fa22ed3-a7e6-4151-955e-3af5b406b56d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='t']</value>
      <webElementGuid>c93100e4-582f-4e20-a60e-fd2d041c1d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel_last_name']/input</value>
      <webElementGuid>8e1eb44b-d58e-42f5-a7dc-c922db137794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/fieldset/input</value>
      <webElementGuid>27740197-9803-4be6-a4e0-8a286fb28daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Last Name']</value>
      <webElementGuid>ad7e0b49-a71c-477f-8731-4a48ff9753f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
