<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputShippingAddress</name>
   <tag></tag>
   <elementGuidId>9d5138c0-1759-40e5-b987-c4ea00d2458d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ant-input.ant-input-status-success.rec.w-100.bp-99</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'address']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dc9708d-7f1a-42e5-af89-03ebff8a1ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>820889a2-544a-4a7a-aea7-013b5f200cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Address</value>
      <webElementGuid>edfebd37-fb92-4d81-a4c7-30be026ef9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success rec w-100 bp-99</value>
      <webElementGuid>1705b1b2-3033-4475-ae78-a1442b7a393c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3cf38e79-ca4b-4920-810d-c1593bbc43a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumberLabel_address&quot;)/input[@class=&quot;ant-input ant-input-status-success rec w-100 bp-99&quot;]</value>
      <webElementGuid>c0dde08b-a0b9-4523-8bff-b4615c425ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='a']</value>
      <webElementGuid>603fd43a-928a-4d95-befc-d9bdb7249ebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel_address']/input</value>
      <webElementGuid>ae74c0e4-8477-4bda-bd16-b8809f3fa26b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/fieldset/input</value>
      <webElementGuid>f6133d4f-1b17-4aa5-b54f-ddd01a987edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Address']</value>
      <webElementGuid>f7a8ee91-df36-418d-9740-de3e2e9f078e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
