<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputShippingApartment</name>
   <tag></tag>
   <elementGuidId>a2899c03-8e20-47f9-bcf3-f4bf83c529a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneNumberLabel_apartment > input.ant-input.ant-input-status-success.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'apartment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>729af96a-1003-47e7-9ab8-b1dc5c8b620a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b226e24-8de5-4f2a-b167-e6a4552dc821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment</value>
      <webElementGuid>5a70544e-7888-4551-9ab6-5c63b61ad21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-status-success w-100</value>
      <webElementGuid>e6bf3d19-39cc-42ae-99db-986aa3a0ce4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>8ad3c31b-03b9-475b-aa6e-41d07eba0791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumberLabel_apartment&quot;)/input[@class=&quot;ant-input ant-input-status-success w-100&quot;]</value>
      <webElementGuid>497a1770-f121-4c14-8f80-db42b592b03d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='t']</value>
      <webElementGuid>0bd32481-244b-4459-bebe-e70b72ec4bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='phoneNumberLabel_apartment']/input</value>
      <webElementGuid>5ed3b102-6003-4b38-8d43-1080cf8ce709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/fieldset/input</value>
      <webElementGuid>5ccd257e-75a6-4718-8861-7b89535b4ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Apartment']</value>
      <webElementGuid>99a608db-835d-4e80-98f8-1cffbdc3f43d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
