<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCardNumber</name>
   <tag></tag>
   <elementGuidId>ea6891c7-6dc4-4877-8fef-5f19e87aa952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38a7735b-9b46-49bc-91fc-1d72e0136d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address </value>
      <webElementGuid>d9d03dc6-409a-4ae6-8f9d-a6aee4e8e1c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf043d76-5f8d-4baa-9059-8d241928abc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card Number</value>
      <webElementGuid>17b19754-76d4-4bf1-aa4c-5fc6411cbdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;secure-container py-5 content-wrapper my-5&quot;]/div[@class=&quot;secure-container__contact-info-container&quot;]/div[@class=&quot;secure-container__contact-info-container__contact-info-wrapper&quot;]/div[@class=&quot;shipping-address-box&quot;]/div[@class=&quot;mt-20 w-100&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;card-wraper&quot;]/fieldset[@class=&quot;custom--fieldset mt-5&quot;]/input[@class=&quot;address&quot;]</value>
      <webElementGuid>b01e5512-8b60-4363-bf7d-ab4cc5a9c089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>912195ab-0e4e-44cc-bc1d-2d19eb613e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div[2]/div/div/fieldset[2]/input</value>
      <webElementGuid>cd789f0e-45b3-47fd-bcf9-25bb14e2f53c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/input</value>
      <webElementGuid>431c0a2e-df67-4e2c-952a-7093e20db0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Card Number']</value>
      <webElementGuid>f0be6a40-67c4-4325-81d4-6a7906a637e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id = 'card']</value>
      <webElementGuid>d4ecbea1-045d-4d72-8d2e-3b7d5be51e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
