<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputCvv</name>
   <tag></tag>
   <elementGuidId>bb539bed-18d5-4365-b5d1-615700ee662e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.address.rec</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'cardCVV']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b84cdcdb-9ff6-4adf-bb1e-f799d15e2a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>address rec</value>
      <webElementGuid>5f00acce-5584-481d-9f21-1d6959c5d80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>07942c3e-87dd-4a1d-9b40-fd56a0a02799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a07f90ba-ca2e-468b-ae9e-f8542fe57f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>edbcd5aa-a8b3-4d6d-8275-ff0093230e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;secure-container py-5 content-wrapper my-5&quot;]/div[@class=&quot;secure-container__contact-info-container&quot;]/div[@class=&quot;secure-container__contact-info-container__contact-info-wrapper&quot;]/div[@class=&quot;shipping-address-box&quot;]/div[@class=&quot;mt-20 w-100&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;card-wraper&quot;]/div[@class=&quot;card-month-mobile d-flex flex-row w-100&quot;]/div[@class=&quot;d-flex w-75&quot;]/fieldset[@class=&quot;custom--fieldset mt-5 w-50 address&quot;]/input[@class=&quot;address rec&quot;]</value>
      <webElementGuid>c3d8e789-1c7e-4023-bdf6-c984eccfc91b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[3]</value>
      <webElementGuid>f7db866a-f46d-4dc3-a1fa-8dd322e2101a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div[2]/div[2]/div/div/div[2]/div/fieldset[2]/input</value>
      <webElementGuid>468237c9-6a7d-47d5-807c-8567e4c594d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset[2]/input</value>
      <webElementGuid>e731b00c-5446-4133-a65d-f42a2fd94f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'CVV']</value>
      <webElementGuid>7f1e3838-a231-41bb-9116-a1107e1033b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@id = 'cardCVV']</value>
      <webElementGuid>9ee5b817-01ef-4add-a872-c1206d5fdd1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
