<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divPrivacyCommunicationPage</name>
   <tag></tag>
   <elementGuidId>4279c8fb-f021-4539-86dd-43306b820a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'Privacy &amp; Communication' or . = 'Privacy &amp; Communication')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9ac33509-d725-4ec5-b337-436f698a0977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy &amp; Communication</value>
      <webElementGuid>0a17ce66-597a-4d80-81be-aa5537c26d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;BOHeaderLayout&quot;]/div[@class=&quot;tabletAndMobileHeader&quot;]/div[@class=&quot;backofficeHeader&quot;]/div[@class=&quot;backofficeHeader__content&quot;]/div[@class=&quot;desktopMenu&quot;]/div[@class=&quot;desktopMenu__content&quot;]/div[@class=&quot;menuLinks&quot;]/ul[1]/a[3]/li[1]</value>
      <webElementGuid>7fe82ef5-d51e-450d-92ea-238a67d03629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div/div/div/div/ul/a[3]/li</value>
      <webElementGuid>d6e62726-57b7-4aed-92cd-18154c74b1b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View My Orders'])[1]/following::li[1]</value>
      <webElementGuid>a10fd832-edb7-4e4f-b654-9081a72f5983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[1]/following::li[2]</value>
      <webElementGuid>da4db13f-530a-4bab-96f6-7b6335246697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Payments'])[1]/preceding::li[1]</value>
      <webElementGuid>4797d8f2-70f9-426a-a416-0697450ac671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/li</value>
      <webElementGuid>36b5d654-f13d-4220-9571-43892ec1eeda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Privacy &amp; Communication' or . = 'Privacy &amp; Communication')]</value>
      <webElementGuid>52a734e6-5c5b-47bd-a12f-23dd6e25bb7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
