<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button3dsSubmitRedirect</name>
   <tag></tag>
   <elementGuidId>4e41bf3d-e841-401f-9158-ae9de97a4626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value= 'Redirect']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7d5046b-b755-4451-86ed-bc6797d09277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn5</value>
      <webElementGuid>4fa7fb0f-0194-4910-9fcd-83f01b8548bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cb797911-c61b-4ffc-ba46-409afda01067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Redirect</value>
      <webElementGuid>d5fb43b6-4400-4133-bcaa-cdf0015a59c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn5&quot;)</value>
      <webElementGuid>74c6a0d6-d48c-43e2-b1c6-38d02430b885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btn5']</value>
      <webElementGuid>9ff5142e-bbd3-4c62-b051-035e8f42db85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formCRes']/input[2]</value>
      <webElementGuid>01696a91-6cb0-48f3-87e3-f227c30d8f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>c221a7e5-862d-4a7f-a15d-041923411a40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'btn5' and @type = 'submit']</value>
      <webElementGuid>f7722b67-4e93-4922-86f4-a3a7876a2d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//input[@value= 'Redirect']</value>
      <webElementGuid>0a591e0a-5b92-4951-88b0-9e9b68d1706b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
